#!/usr/bin/env bash
#
# build.sh — configure and build PaperBoat with its own CMake presets.
# Fetches the pinned source first when PaperBoat/ is missing, so a fresh
# clone of imps needs only this script (plus installdependencies.sh once)
# to get to a built game.
#
# Mirrors upstream's documented Linux build (docs/BUILDING.md + the
# build-linux CI job): the `ninja-release` preset, which puts the build in
# PaperBoat/build/ninja-release.  The port asset archive paperboat.o2r is
# generated by the GeneratePortO2R target, which the main target depends on,
# so a plain build produces it (no ROM required); the ROM-extracted pm64.o2r
# is created in-app on first run instead.
#
# Caveat: the configure/build step needs network (libultraship downloads
# gamecontrollerdb.txt).

set -e
cd "$(dirname "$0")"

[ -d PaperBoat ] || ./fetch.sh

cd PaperBoat

# Configure (Release) and build. binaryDir for this preset is
# PaperBoat/build/ninja-release (see CMakePresets.json).
cmake --preset ninja-release
cmake --build build/ninja-release --parallel "$(nproc)"
