#!/usr/bin/env bash
# asmdiff.sh — the behaviour-preservation gate for the standard-C rewrites: compile ONE decomp
# source file twice with the build's exact flags — as it is in the working tree, and as it was at
# a git ref — to assembly, and diff. An EMPTY diff proves the rewrite generated byte-identical
# code (the strongest oracle a syntactic cleanup can have); a non-empty diff is not automatically
# wrong (a goto→loop rewrite may legitimately reschedule instructions) but must be read and
# explained in the patch's commit message.
#
#   bash tools/asmdiff.sh src/game/mario.c [<ref>=HEAD] [<build dir>]
#
# <build dir> is a configured cmake tree of the checkout (default $ASMDIFF_BUILD); its
# compile_commands.json supplies the flags (configure with -DCMAKE_EXPORT_COMPILE_COMMANDS=ON).
#
# Two kinds of file:
#   - a translation unit (has a compile command): the version at <ref> is written next to the
#     real file under a temp name (same directory, so relative #includes resolve identically).
#   - an included file (`*.inc.c`, no compile command of its own): every TU that #includes it is
#     compiled twice, with the <ref> version swapped into the real path for the "before" compile
#     and the working-tree version restored afterwards (the restore also runs on any exit).
# __LINE__ is pinned to 0 for both compiles (Ghostship macros such as CALL_EVENT bake it into an
# integer argument, so an edit that shifts lines would otherwise read as a codegen change), and
# .file/.ident directives plus __FILE__ strings are normalised away.
#
# Project selection (2026-09-22, the OoT twin reuses this gate): ASMDIFF_PROJECT=SuperMario64
# (default; checkout Ghostship/, sources under src/) or OcarinaOfTime (checkout Shipwright/,
# sources under soh/src/). <path> is always relative to the checkout root.
set -u
cd "$(dirname "$0")/.."                             # repo root
case "${ASMDIFF_PROJECT:-SuperMario64}" in
    SuperMario64)  GS=n64/SuperMario64/Ghostship;   SRCROOT=src ;;
    OcarinaOfTime) GS=n64/OcarinaOfTime/Shipwright; SRCROOT=soh/src ;;
    *) echo "ASMDIFF_PROJECT must be SuperMario64 or OcarinaOfTime" >&2; exit 2 ;;
esac
src=${1:?usage: asmdiff.sh <path under the checkout/> [ref] [build dir]}
ref=${2:-HEAD}
build=${3:-${ASMDIFF_BUILD:-}}
[ -n "$build" ] || { echo "set ASMDIFF_BUILD or pass a configured build dir" >&2; exit 2; }
[ -f "$build/compile_commands.json" ] || { echo "no compile_commands.json in $build" >&2; exit 2; }
gsabs=$(cd "$GS" && pwd)
abs_src=$gsabs/$src

# ASMDIFF_CMD_FROM=<path under the checkout>: take the compile command recorded for THAT file
# instead (for a file the series RENAMED after the build tree was configured — the flags are the
# same for every decomp TU, only the -c/-o operands differ, and those are replaced anyway).
compile_cmd() { # <abs TU path> -> the recorded command, or fails
    [ -z "${ASMDIFF_CMD_FROM:-}" ] || set -- "$gsabs/$ASMDIFF_CMD_FROM"
    python3 - "$build/compile_commands.json" "$1" <<'PY'
import json, sys
cc = json.load(open(sys.argv[1]))
m = [e for e in cc if e["file"] == sys.argv[2]]
if not m:
    sys.exit(1)
e = m[0]
print(e.get("command") or " ".join(e["arguments"]))
PY
}
normalise() { python3 "$(dirname "$0")/asmdiff_normalise.py" "$1"; }
compile() { # <cmd> <source> <out.s>
    local cmd=$1
    cmd=$(printf '%s' "$cmd" | sed -E 's/ -o [^ ]+//; s/ -c [^ ]+//; s/ -MD//; s/ -MT [^ ]+//; s/ -MF [^ ]+//')
    ( cd "$build" && eval "$cmd" -D__LINE__=0 -Wno-builtin-macro-redefined -S -o "$3" -c "$2" ) 2>"$tmpdir/err" || { cat "$tmpdir/err" >&2; return 1; }
    normalise "$3"
}
report() { # <label> <before.s> <after.s> -> 0 identical, 3 differs
    if diff -q "$2" "$3" >/dev/null; then
        echo "IDENTICAL codegen: $1 (working tree vs $ref)"; return 0
    fi
    echo "CODEGEN DIFFERS: $1 (working tree vs $ref) — $(diff "$2" "$3" | grep -c '^[<>]') changed asm lines; first hunk:"
    diff "$2" "$3" | head -40; return 3
}

tmpdir=$(mktemp -d)
restore=""
cleanup() { [ -n "$restore" ] && cp "$restore" "$abs_src"; rm -rf "$tmpdir"; rm -f "$(dirname "$abs_src")/.asmdiff_tmp_$$.c"; }
trap cleanup EXIT

if cmd=$(compile_cmd "$abs_src"); then
    # a translation unit: temp copy of the old version beside the real file
    git -C "$GS" show "$ref:$src" > "$(dirname "$abs_src")/.asmdiff_tmp_$$.c" || exit 2
    compile "$cmd" "$(dirname "$abs_src")/.asmdiff_tmp_$$.c" "$tmpdir/before.s" || exit 1
    compile "$cmd" "$abs_src" "$tmpdir/after.s" || exit 1
    report "$src" "$tmpdir/before.s" "$tmpdir/after.s"; exit $?
fi

# an included file: find every TU that includes it, swap the old version in for "before"
base=$(basename "$src")
includers=$(grep -rl -E "#include +\"([^\"]*/)?$base\"" "$gsabs/$SRCROOT" --include='*.c' | grep -v '\.inc\.c$' || true)
[ -n "$includers" ] || { echo "no compile command and no includer found for $src" >&2; exit 2; }
cp "$abs_src" "$tmpdir/current.c"; restore="$tmpdir/current.c"
git -C "$GS" show "$ref:$src" > "$tmpdir/old.c" || exit 2
status=0
for tu in $includers; do
    tucmd=$(compile_cmd "$tu") || { echo "  (no compile command for includer $tu, skipped)"; continue; }
    cp "$tmpdir/old.c" "$abs_src"
    compile "$tucmd" "$tu" "$tmpdir/before.s" || { status=1; break; }
    cp "$tmpdir/current.c" "$abs_src"
    compile "$tucmd" "$tu" "$tmpdir/after.s" || { status=1; break; }
    report "$src (via ${tu#$gsabs/})" "$tmpdir/before.s" "$tmpdir/after.s" || status=3
done
cp "$tmpdir/current.c" "$abs_src"; restore=""
exit $status
