#!/usr/bin/env bash
# asmdiff.sh — the behaviour-preservation gate for the standard-C rewrites: compile ONE decomp
# source file twice with the build's exact flags — as it is in the working tree, and as it was at
# a git ref — to assembly, and diff. An EMPTY diff proves the rewrite generated byte-identical
# code (the strongest oracle a syntactic cleanup can have); a non-empty diff is not automatically
# wrong (a goto→loop rewrite may legitimately reschedule instructions) but must be read and
# explained in the patch's commit message.
#
#   bash tasks/adhoc/mario64-assembly-isms/asmdiff.sh src/game/mario.c [<ref>=HEAD] [<build dir>]
#
# <build dir> is a configured cmake tree of the checkout (default $ASMDIFF_BUILD or a scratch
# tree); its compile_commands.json supplies the flags. The file at <ref> is written next to the
# real file (same directory, so relative #includes resolve identically) under a temp name and
# removed afterwards. Requires: cmake configured with -DCMAKE_EXPORT_COMPILE_COMMANDS=ON.
set -u
cd "$(dirname "$0")/../../.."                       # repo root
GS=n64/SuperMario64/Ghostship
src=${1:?usage: asmdiff.sh <path under Ghostship/> [ref] [build dir]}
ref=${2:-HEAD}
build=${3:-${ASMDIFF_BUILD:-}}
[ -n "$build" ] || { echo "set ASMDIFF_BUILD or pass a configured build dir" >&2; exit 2; }
[ -f "$build/compile_commands.json" ] || { echo "no compile_commands.json in $build" >&2; exit 2; }

abs_src=$(cd "$GS" && pwd)/$src
cmd=$(python3 - "$build/compile_commands.json" "$abs_src" <<'PY'
import json, sys
cc = json.load(open(sys.argv[1]))
m = [e for e in cc if e["file"] == sys.argv[2]]
if not m:
    sys.exit("no compile command for " + sys.argv[2])
e = m[0]
print(e.get("command") or " ".join(e["arguments"]))
PY
) || exit 2
# strip the output object and the source from the recorded command; we supply our own
cmd=$(printf '%s' "$cmd" | sed -E 's/ -o [^ ]+//; s/ -c [^ ]+//; s/ -MD//; s/ -MT [^ ]+//; s/ -MF [^ ]+//')

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir" "$(dirname "$abs_src")/.asmdiff_tmp_$$.c"' EXIT
git -C "$GS" show "$ref:$src" > "$(dirname "$abs_src")/.asmdiff_tmp_$$.c" || exit 2

compile() { # <source> <out.s>
    ( cd "$build" && eval "$cmd" -S -o "$2" -c "$1" ) 2>"$tmpdir/err" || { cat "$tmpdir/err" >&2; return 1; }
    # normalise what legitimately differs between the two compiles: the .file directive, the
    # .ident line, and the __FILE__/__LINE__ strings that assert/log macros embed (the path
    # differs between the temp copy and the real file; line numbers shift on any edit)
    sed -i -E '/^\s*\.file\s/d; /^\s*\.ident/d; s#(/[^"]*)?\.asmdiff_tmp_[0-9]+\.c#SRC#g; s#/[^"]*/Ghostship/src/[^":]*\.c#SRC#g; s#SRC:[0-9]+#SRC:N#g' "$2"
}
compile "$(dirname "$abs_src")/.asmdiff_tmp_$$.c" "$tmpdir/before.s" || exit 1
compile "$abs_src" "$tmpdir/after.s" || exit 1

if diff -q "$tmpdir/before.s" "$tmpdir/after.s" >/dev/null; then
    echo "IDENTICAL codegen: $src (working tree vs $ref)"
    exit 0
else
    echo "CODEGEN DIFFERS: $src (working tree vs $ref) — $(diff "$tmpdir/before.s" "$tmpdir/after.s" | grep -c '^[<>]') changed asm lines; first hunk:"
    diff "$tmpdir/before.s" "$tmpdir/after.s" | head -40
    exit 3
fi
